name: 'Bumpver Tag'
description: 'Increments semver repository tag based on commit message (#major, #minor, defaults to #patch)'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
