name: 'Bumpver Tag'
description: 'Increments semver repository tag based on commit message (#major, #minor, defaults to #patch)'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to push new tag'
    required: true
  DRY_RUN:
    description: 'Run the action in dry-run mode'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  args:
    - "--dry-run=${{ inputs.DRY_RUN }}"
